services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"   # expose if you want external access; remove if not needed
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot_pass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-changeme}"]
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-changeme}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  lumen:
    build:
      context: ./lumen-api
      dockerfile: Dockerfile
    environment:
      APP_NAME: EnergeX
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost
      APP_TIMEZONE: UTC

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-app}
      DB_PASSWORD: ${DB_PASSWORD:-app_pass}

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync

      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL:-3600}

      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD:-changeme}
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  node:
    build:
      context: ./node-graphql
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-app}
      DB_PASSWORD: ${DB_PASSWORD:-app_pass}

      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL:-3600}

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-changeme}
    depends_on:
      - mysql
      - redis
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/graphql?health=1"]
      interval: 15s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
    depends_on:
      - lumen
      - node
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: